sudo: false

language: node_js

node_js:
  - "10"

services:
  - docker

script:
  - yarn build

notifications:
  email:
    - shun10116@gmail.com
  slack:
    rooms:
      - hi-cordworkspace:EC6Q4SIRTddzUEE0rMDXrSl6#dev-travis
