# @See
## https://docs.travis-ci.com/user/encrypting-files/
sudo: required

language: node_js

node_js:
  - "10"

services:
  - docker

jobs:
  include:
    #############################
    # Install and Test
    #############################
    ## API Server
    - stage: api-server-install-test
      script:
        - cd api-server
        - yarn install
        - yarn test

    ## Home
    - stage: home-install-test
      script:
        - cd home
        - yarn install
        - yarn test

    ## Communities
    - stage: communities-install-test
      script:
        - cd communities
        - yarn install
        - yarn test

notifications:
  email:
    - shun10116@gmail.com
  slack:
    rooms:
      - hi-cordworkspace:EC6Q4SIRTddzUEE0rMDXrSl6#dev-travis
