# @See
## https://docs.travis-ci.com/user/encrypting-files/
sudo: required

language: node_js

node_js:
  - "10"

services:
  - docker

jobs:
  include:
    #############################
    # Install and Test
    #############################
    - stage: Tests
      name: API server Unit Test
      script:
        - cd api-server
        - yarn install
        - yarn test

    - stage: Tests
      name: Home client Unit Test
      script:
        - cd home
        - yarn install
        - yarn test

    - stage: Tests
      name: Communities client Unit Test
      script:
        - cd communities
        - yarn install
        - yarn test

notifications:
  email:
    - shun10116@gmail.com
  slack:
    rooms:
      - hi-cordworkspace:EC6Q4SIRTddzUEE0rMDXrSl6#dev-travis
