version: "3.7"
services:
  # GATEWAY
  gateway-nginx:
    build:
      context: ./gateway/nginx
    ports:
      - 80:80
    links:
      - gateway
      - home-nginx
      - communities-nginx

  gateway:
    build:
      context: ./gateway
    ports:
      - 3000:3000
    links:
      - home-nginx
      - communities-nginx

  # HOME
  home-nginx:
    build:
      context: ./home/nginx
    ports:
      - 4080:4080
    links:
      - home

  home:
    build:
      context: ./home
    ports:
      - 4000:4000

  # COMMUNITIES
  communities-nginx:
    build:
      context: ./communities/nginx
    ports:
      - 5080:5080
    links:
      - communities

  communities:
    build:
      context: ./communities
    ports:
      - 5000:5000
