version: "3.7"
services:
  # GATEWAY
  gateway-nginx:
    build:
      context: ./gateway/nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    links:
      - gateway

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    links:
      - home-nginx
      - communities-nginx

  # HOME
  home-nginx:
    build:
      context: ./home/nginx
      dockerfile: Dockerfile
    links:
      - home

  home:
    build:
      context: ./home
      dockerfile: Dockerfile

  # COMMUNITIES
  communities-nginx:
    build:
      context: ./communities/nginx
      dockerfile: Dockerfile
    links:
      - communities

  communities:
    build:
      context: ./communities
      dockerfile: Dockerfile
