version: "3.7"
services:
  load-balancer-nginx:
    build:
      context: ./load-balancer/nginx
    ports:
      - 80:80
    links:
      - api-server-nginx
      - home-nginx
      - communities-nginx

  api-server-nginx:
    build:
      context: ./api-server/nginx
    ports:
      - 3080:3080
    links:
      - api-server

  api-server:
    build:
      context: ./api-server
    ports:
      - 3000:3000

  home-nginx:
    build:
      context: ./home/nginx
    ports:
      - 4080:4080
    links:
      - home

  home:
    build:
      context: ./home
    ports:
      - 4000:4000

  communities-nginx:
    build:
      context: ./communities/nginx
    ports:
      - 5080:5080
    links:
      - communities

  communities:
    build:
      context: ./communities
    ports:
      - 5000:5000
