version: "3.7"
services:
  elb-nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    links:
      - elb
      - home
      - communities

  elb:
    build:
      context: ./elb
      dockerfile: Dockerfile

  home:
    build:
      context: ./home
      dockerfile: Dockerfile

  communities:
    build:
      context: ./communities
      dockerfile: Dockerfile
