version: "3.7"
services:
  mariadb:
    build: ./db
    ports:
      - ${DB_PORT}
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${DB_DATABASE}
    env_file:
      - .env

  server:
    build: ./
    env_file:
      - .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - ${DB_HOST}
    links:
      - mariadb
