version: "3.7"
services:
  # GATEWAY
  gateway-nginx:
    build:
      context: ./gateway-nginx
    ports:
      - 80:80
    links:
      - gateway
      - home
      - communities

  gateway:
    build:
      context: ./gateway
    links:
      - home-nginx
      - communities-nginx
    ports:
      - 3000:3000

  # HOME
  home-nginx:
    build:
      context: ./home/nginx
    links:
      - home
    ports:
      - 4080:4080

  home:
    build:
      context: ./home
    ports:
      - 4000:4000

  # COMMUNITIES
  communities-nginx:
    build:
      context: ./communities/nginx
    links:
      - communities
    ports:
      - 5080:5080

  communities:
    build:
      context: ./communities
    ports:
      - 5000:5000
