version: "3.7"
services:
  # ELB
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
  gateway-nginx:
    build:
      context: ./gateway/nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    links:
      - gateway

  # HOME
  home:
    build:
      context: ./home
      dockerfile: Dockerfile
  home-nginx:
    build:
      context: ./home/nginx
      dockerfile: Dockerfile
    ports:
      - 4080:4080
    links:
      - home

  # COMMUNITIES
  communities:
    build:
      context: ./communities
      dockerfile: Dockerfile
  communities-nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 5080:5080
    links:
      - communities
